clc;
clear all;
close all;
I=imread('circles.png');
figure(1);imshow(I);title('original image');
SE1 = strel('disk',1);
op_erode_cir = imerode(I,SE1);
figure(2);
subplot(3,2,1);
imshow(op_erode_cir);
title('erosion SE - Circle with size 1');
SE2 = strel('disk',3);
op2 = imerode(I,SE2);
subplot(3,2,2);
imshow(op2);
title('erosion SE - Circle with size 3');
SE3 = strel('line',10,0);
op3 = imerode(I,SE3);
subplot(3,2,3);
imshow(op3);
title('erosion SE - Line with length 10 angle 0 degree');
SE4 = strel('line',10,90);
op4 = imerode(I,SE4);
subplot(3,2,4);
imshow(op4);
title('erosion SE - Line with length 10 angle 90 degree');
SE5 = strel('disk',1);
op_erode_cir5 = imdilate(I,SE5);
subplot(3,2,5);
imshow(op_erode_cir5);
title(' dilation SE - Circle with size 1');
SE6 = strel('line',10,90);
op6 = imdilate(I,SE6);
subplot(3,2,6);
imshow(op6);
title('dilation SE - Line with length 10 angle 90 degree');